server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/companies/**
          filters:
            - StripPrefix=1

        - id: milk-service
          uri: http://localhost:8085
          predicates:
            - Path=/milk/**
          filters:
            - StripPrefix=1

        - id: health-service
          uri: http://localhost:8086
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=1

        - id: distributor-service
          uri: http://localhost:8091
          predicates:
            - Path=/distributors/**
          filters:
            - StripPrefix=1

        - id: finance-service
          uri: http://localhost:8090
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8092
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
